//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scannit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scannit.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires: .
        /// </summary>
        public static string ExpiresLiteral {
            get {
                return ResourceManager.GetString("ExpiresLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last top-up.
        /// </summary>
        public static string LastTopUpHeader {
            get {
                return ResourceManager.GetString("LastTopUpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap your card against your NFC reader.
        /// </summary>
        public static string ScanCardPrompt {
            get {
                return ResourceManager.GetString("ScanCardPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days and paid .
        /// </summary>
        public static string SeasonPassDaysAndPaid {
            get {
                return ResourceManager.GetString("SeasonPassDaysAndPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days remaining.
        /// </summary>
        public static string SeasonPassDaysRemaining {
            get {
                return ResourceManager.GetString("SeasonPassDaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string SeasonPassExpired {
            get {
                return ResourceManager.GetString("SeasonPassExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Pass.
        /// </summary>
        public static string SeasonPassHeader {
            get {
                return ResourceManager.GetString("SeasonPassHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h, {1}min remaining.
        /// </summary>
        public static string SeasonPassHoursRemaining {
            get {
                return ResourceManager.GetString("SeasonPassHoursRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last renewed.
        /// </summary>
        public static string SeasonPassLastRenewed {
            get {
                return ResourceManager.GetString("SeasonPassLastRenewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On .
        /// </summary>
        public static string SeasonPassOn {
            get {
                return ResourceManager.GetString("SeasonPassOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , which cost .
        /// </summary>
        public static string SeasonPassYouAdded {
            get {
                return ResourceManager.GetString("SeasonPassYouAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueHeader {
            get {
                return ResourceManager.GetString("ValueHeader", resourceCulture);
            }
        }
    }
}
